### ISSUE TITLE
Installer stops with newest version of nutshell-kit 

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/euf_nutshell_installer#2]
i wanted to install a project with the newest version of the nutshell framework (to use gulp 4 etc). 

Composer runs successfully until the configuration begins:

```
Please customize your Contao nutshell. Skip questions by clicking enter. Yellow values are default values.
package.name (euf_nutshell_kit) <- How would you like to name your project?:
gulpfile.themePath () <- How would you like to name the folder with all theme files?: theme
gulpfile.bsProxy () <- For local development, what will be the uri of the installation?: nutshell-test2.localhost


  [ErrorException]
  copy(): Filename cannot be empty

```
As you see, there are no suggestions for themePath and bsProxy.  Can this be the problem? I compared this to a stable version, where this suggestions still exists. 

My workaround for now: i restart `composer install` to complete the installation

**Comment by richardhj** [comment]
Did you run composer create-project? It works for me.
Them I switched to euf-nutshell:dev-develop. Setup runs as well.

**Comment by richardhj** [comment]
See #3.

**Comment by denniserdmann** [comment]
i used `composer create-project erdmannfreunde/euf_nutshell_kit:dev-develop  project`.

How can i check a PR in this constellation? Is it even possible to create a project with a PR? Or do we need to merge your request first?

**Comment by richardhj** [comment]
I released a new version of the installer and updated the nutshell-kit in https://github.com/ErdmannFreunde/euf_nutshell_kit/commit/2ab1500a7ae24f6d7854d4e13075754e45ada236.
You can check if everything works and close the issue.

**Comment by denniserdmann** [comment]
Nope, same problem still persists. Using 
`composer create-project erdmannfreunde/euf_nutshell_kit:dev-develop project`
which loaded `erdmannfreunde/euf_nutshell_installer (v0.3.1)` so i think it's not a caching problem.

Suggestions (in yellow) are still missing, too

![image](https://user-images.githubusercontent.com/3773697/59434179-538b9b80-8deb-11e9-8a62-1330effb516f.png)

**Comment by richardhj** [comment]
Fixed and verified that it works 👍
